services:
  - type: web
    name: cvk-demo-site
    runtime: static
    branch: main
    rootDir: app 2
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
